# -*- coding: utf-8 -*-
"""visual-computing-25ai60r20-25ai60r11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kA88fQgPoAp7PQj-xEI44bw_Upeouf4B
"""

!pip install keras-flops

"""**1. IMPORTS**"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
np.random.seed(2)

import os
import random
import itertools
import time

from PIL import Image, ImageChops, ImageEnhance

import tensorflow as tf
import tensorflow_hub as hub

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam

from tensorflow.keras import layers
from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2

"""**2. ERROR LEVEL ANALYSIS (ELA) FUNCTION**"""

def convert_to_ela_image(path, quality=90):
    """
    (2.1) Recompress image → detect compression differences
    (2.2) Highlight tampered regions by difference mapping
    (2.3) Scale differences for visibility
    """
    temp_filename = 'temp_file_name.jpg'

    image = Image.open(path).convert('RGB')
    image.save(temp_filename, 'JPEG', quality=quality)
    temp_image = Image.open(temp_filename)

    ela_image = ImageChops.difference(image, temp_image)

    extrema = ela_image.getextrema()
    max_diff = max([ex[1] for ex in extrema])
    if max_diff == 0: max_diff = 1

    scale = 255.0 / max_diff
    ela_image = ImageEnhance.Brightness(ela_image).enhance(scale)
    return ela_image

"""**3. IMAGE PREPROCESSING**"""

image_size = (224, 224)

def prepare_image(image_path):
    """
    (3.1) Convert to ELA → resize
    (3.2) Convert to NumPy → MobileNetV2 preprocessing
    """
    ela_image = convert_to_ela_image(image_path, 90).resize(image_size)
    img_array = np.array(ela_image, dtype=np.float32)
    img_array = tf.keras.applications.mobilenet_v2.preprocess_input(img_array)
    return img_array

"""**4. VISUAL CHECK (Optional)**"""

real_image_path = '/kaggle/input/casia-dataset/casia/CASIA2/Au/Au_ani_00001.jpg'
fake_image_path = '/kaggle/input/casia-dataset/casia/CASIA2/Tp/Tp_D_NRN_S_N_ani10171_ani00001_12458.jpg'

print("Original Real Image:")
display(Image.open(real_image_path))
print("ELA of Real Image:")
display(convert_to_ela_image(real_image_path, 90))

print("Original Fake Image:")
display(Image.open(fake_image_path))
print("ELA of Fake Image:")
display(convert_to_ela_image(fake_image_path, 90))

"""**5. LOAD CASIA DATASET (REAL=1, FAKE=0)**"""

X, Y = [], []
path_au = "/kaggle/input/casia-dataset/CASIA2/Au/"
path_tp = "/kaggle/input/casia-dataset/CASIA2/Tp/"

print("Loading Real Images...")
for dirname, _, files in os.walk(path_au):
    for f in files:
        if f.endswith(("jpg", "png")):
            X.append(prepare_image(os.path.join(dirname, f)))
            Y.append(1)

# (5.1) Shuffle + Limit real images to 2100
temp = list(zip(X, Y))
random.shuffle(temp)
X, Y = zip(*temp)
X, Y = list(X)[:2100], list(Y)[:2100]

print("Real Images Loaded:", len(X))

print("Loading Fake Images...")
for dirname, _, files in os.walk(path_tp):
    for f in files:
        if f.endswith(("jpg", "png")):
            X.append(prepare_image(os.path.join(dirname, f)))
            Y.append(0)

print("TOTAL IMAGES:", len(X))

X = np.array(X)
Y = to_categorical(Y, 2)

"""**6. TRAIN-TEST SPLIT**"""

X_train, X_val, Y_train, Y_val = train_test_split(X, Y, test_size=0.2, random_state=42)

"""**7. CUSTOM RESNET BLOCKS (for ResNet18/34)**"""

def resnet_block(x, filters, stride=1):
    """
    (7.1) Standard residual block
    """
    shortcut = x

    x = layers.Conv2D(filters, 3, strides=stride, padding="same")(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)

    x = layers.Conv2D(filters, 3, padding="same")(x)
    x = layers.BatchNormalization()(x)

    # (7.2) Projection shortcut when channel counts differ
    if stride != 1 or shortcut.shape[-1] != filters:
        shortcut = layers.Conv2D(filters, 1, strides=stride, padding="same")(shortcut)
        shortcut = layers.BatchNormalization()(shortcut)

    x = layers.Add()([x, shortcut])
    return layers.ReLU()(x)

def build_resnet(input_shape, num_blocks_list, num_classes=2):
    """
    (7.3) Build full ResNet architecture from block lists
    """
    inputs = layers.Input(shape=input_shape)
    x = layers.Conv2D(64, 7, strides=2, padding="same")(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D(3, strides=2, padding="same")(x)

    filters = 64
    for block_count in num_blocks_list:
        for b in range(block_count):
            stride = 2 if (b == 0 and filters != 64) else 1
            x = resnet_block(x, filters, stride)
        filters *= 2

    x = layers.GlobalAveragePooling2D()(x)
    x = Dense(256, activation='relu')(x)
    x = Dropout(0.5)(x)
    outputs = Dense(num_classes, activation='softmax')(x)

    return Model(inputs, outputs)

def ResNet18(input_shape=(224,224,3), num_classes=2):
    return build_resnet(input_shape, [2,2,2,2], num_classes)

def ResNet34(input_shape=(224,224,3), num_classes=2):
    return build_resnet(input_shape, [3,4,6,3], num_classes)

"""**8. MODEL BUILDER (All 5 Models)**"""

def build_model(model_name, input_shape=(224,224,3)):

    if model_name == "resnet18":
        print("Using custom ResNet-18...")
        return ResNet18(input_shape)

    if model_name == "resnet34":
        print("Using custom ResNet-34...")
        return ResNet34(input_shape)

    if model_name == "resnet50":
        base = tf.keras.applications.ResNet50(include_top=False, weights="imagenet",
                                              input_shape=input_shape)
        base.trainable = False
        x = GlobalAveragePooling2D()(base.output)
        x = Dense(256, activation='relu')(x)
        x = Dropout(0.5)(x)
        out = Dense(2, activation='softmax')(x)
        return Model(base.input, out)

    if model_name == "mobilenetv2":
        base = tf.keras.applications.MobileNetV2(include_top=False, weights="imagenet",
                                                 input_shape=input_shape)
        base.trainable = False
        x = GlobalAveragePooling2D()(base.output)
        x = Dense(128, activation='relu')(x)
        x = Dropout(0.5)(x)
        out = Dense(2, activation='softmax')(x)
        return Model(base.input, out)

    if model_name == "efficientnetlite":
        eff = hub.KerasLayer(
            "https://tfhub.dev/tensorflow/efficientnet/lite0/feature-vector/2",
            trainable=False
        )
        return Sequential([
            layers.InputLayer(input_shape=input_shape),
            eff,
            Dense(128, activation='relu'),
            Dropout(0.5),
            Dense(2, activation='softmax')
        ])

    raise ValueError("Unknown model name")

"""**9. TRAINING + METRIC COLLECTION**"""

def train_evaluate(model_name):

    print("\n")
    print(f"Training: {model_name}")
    print("\n")

    # (9.1) Build + compile
    model = build_model(model_name)
    model.compile(optimizer=Adam(1e-3),loss="binary_crossentropy",metrics=["accuracy"])

    es = EarlyStopping(patience=3, restore_best_weights=True)

    # (9.2) Train
    history = model.fit(
        X_train, Y_train,
        validation_data=(X_val, Y_val),
        epochs=15,
        batch_size=32,
        callbacks=[es],
        verbose=1
    )

    # (9.3) Accuracy & Confusion Matrix
    Y_pred = model.predict(X_val)
    preds = np.argmax(Y_pred, axis=1)
    labels = np.argmax(Y_val, axis=1)
    acc = accuracy_score(labels, preds)

    cm = confusion_matrix(labels, preds)

    # Confusion matrix plot
    plt.figure(figsize=(4,4))
    plt.imshow(cm, cmap="Blues")
    plt.title(f"{model_name} Confusion Matrix")
    plt.xticks([0,1], ["Fake","Real"])
    plt.yticks([0,1], ["Fake","Real"])
    for i in range(2):
        for j in range(2):
            plt.text(j,i, cm[i,j], ha="center", va="center")
    plt.show()

    # (9.4) Inference time (ms)
    t0 = time.time()
    model.predict(X_val[:1])
    t1 = time.time()
    infer_ms = (t1 - t0) * 1000

    # (9.5) FLOPs
    try:
        from keras_flops import get_flops
        flops = get_flops(model, batch_size=1)
    except:
        flops = -1

    # (9.6) Params + Size
    params = model.count_params()
    model.save(f"{model_name}.h5")
    size_mb = os.path.getsize(f"{model_name}.h5") / (1024*1024)

    return {
        "name": model_name,
        "accuracy": acc,
        "inference_ms": infer_ms,
        "params": params,
        "model_size": size_mb,
        "flops": flops,
        "history": history
    }

"""**10. TRAIN ALL MODELS**"""

model_names = ["resnet18", "resnet34", "resnet50", "mobilenetv2", "efficientnetlite"]

results = []
for m in model_names:
    results.append(train_evaluate(m))

"""**11. PLOT VALIDATION ACCURACY CURVES**"""

plt.figure(figsize=(8,5))
for r in results:
    plt.plot(r["history"].history["val_accuracy"], label=r["name"])
plt.title("Validation Accuracy Comparison")
plt.xlabel("Epoch")
plt.ylabel("Val Accuracy")
plt.legend()
plt.show()

"""**12. FINAL MODEL COMPARISON TABLE**"""

print("\n\n FINAL MODEL COMPARISON \n")
print("{:<15} {:<12} {:<12} {:<12} {:<15} {:<15}".format(
    "Model","Accuracy","Infer(ms)","Params","Size(MB)","FLOPs"
))
print("-"*100)

for r in results:
    print("{:<15} {:<12.3f} {:<12.2f} {:<12} {:<15.2f} {:<15}".format(
        r["name"], r["accuracy"], r["inference_ms"],
        r["params"], r["model_size"], r["flops"]
    ))

